// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_guild
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-25, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `turbineblade`, CPU: `AMD Ryzen 5 3600 6-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_guild
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 20
// --template
// frame-weight-template.hbs
// --output
// ./pallets/pallet-guild/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_guild.
pub trait WeightInfo {
	fn create_guild() -> Weight;
	fn join_guild() -> Weight;
}

/// Weights for pallet_guild using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Guild Guilds (r:1 w:1)
	fn create_guild() -> Weight {
		(16_902_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Guild Guilds (r:1 w:0)
	// Storage: Guild NextRequestIdentifier (r:1 w:1)
	// Storage: Chainlink Operators (r:1 w:0)
	// Storage: Chainlink NextOperator (r:1 w:1)
	// Storage: Chainlink NextRequestIdentifier (r:1 w:1)
	// Storage: Guild JoinRequests (r:0 w:1)
	// Storage: Chainlink Requests (r:0 w:1)
	fn join_guild() -> Weight {
		(46_287_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Guild Guilds (r:1 w:1)
	fn create_guild() -> Weight {
		(16_902_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Guild Guilds (r:1 w:0)
	// Storage: Guild NextRequestIdentifier (r:1 w:1)
	// Storage: Chainlink Operators (r:1 w:0)
	// Storage: Chainlink NextOperator (r:1 w:1)
	// Storage: Chainlink NextRequestIdentifier (r:1 w:1)
	// Storage: Guild JoinRequests (r:0 w:1)
	// Storage: Chainlink Requests (r:0 w:1)
	fn join_guild() -> Weight {
		(46_287_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
}
