FROM rustlang/rust:nightly-slim AS build

RUN apt update -y \
    && apt upgrade -y \
    && apt install build-essential git librocksdb-dev clang cmake llvm llvm-dev libssl-dev pkg-config protobuf-compiler -y

RUN rustup target add wasm32-unknown-unknown --toolchain nightly

WORKDIR /opt/app
COPY . .

ENV RUSTFLAGS=-Dwarnings

RUN cargo fmt -- --check 

# without features
RUN cargo check --color=always --tests --examples

# with runtime benchmarks
RUN cargo check --color=always --tests --examples --features runtime-benchmarks

# with try-runtime
RUN cargo check --color=always --tests --examples --features try-runtime

RUN cargo clippy --color=always --tests --examples --all-features

RUN cargo test --release --all-features --workspace --exclude gn-node --exclude gn-wasm --exclude gn-frontend
