FROM rustlang/rust:nightly-slim AS build

RUN apt update -y \
    && apt upgrade -y \
    && apt install build-essential git librocksdb-dev clang cmake llvm llvm-dev libssl-dev pkg-config -y

RUN rustup target add wasm32-unknown-unknown --toolchain nightly

WORKDIR /opt/app
COPY . .
ENV RUSTFLAGS=-Dwarnings

RUN cargo fmt -- --check 

RUN cargo clippy --color=always --all-features --tests

RUN cargo test --all-features --workspace --exclude gn-node
