
//! Autogenerated weights for `pallet_guild`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 19.0.0
//! DATE: 2023-04-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `turbineblade`, CPU: `AMD Ryzen 5 3600 6-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/gn-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_guild
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 20
// --output
// ./gn-pallets/pallet-guild/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn create_guild(n: u32, ) -> Weight;
	fn create_free_role() -> Weight;
	fn create_role_with_allowlist(n: u32, r: u32, s: u32, ) -> Weight;
	fn create_child_role(r: u32, s: u32, ) -> Weight;
	fn create_unfiltered_role(r: u32, s: u32, ) -> Weight;
	fn join_free_role() -> Weight;
	fn join_child_role() -> Weight;
	fn join_role_with_allowlist() -> Weight;
	fn join_unfiltered_role() -> Weight;
	fn leave() -> Weight;
	fn request_access_check() -> Weight;
}

/// Weight functions for `pallet_guild`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Guild GuildIdMap (r:1 w:1)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Guilds (r:0 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 256]`.
	fn create_guild(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `6404`
		// Minimum execution time: 25_919 nanoseconds.
		Weight::from_parts(26_956_537, 6404)
			// Standard Error: 191
			.saturating_add(Weight::from_ref_time(2_281).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 37_861 nanoseconds.
		Weight::from_parts(38_603_000, 14399)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[1, 128]`.
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_role_with_allowlist(n: u32, r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 53_902 nanoseconds.
		Weight::from_parts(42_366_297, 14399)
			// Standard Error: 1_800
			.saturating_add(Weight::from_ref_time(1_500_863).saturating_mul(n.into()))
			// Standard Error: 21_769
			.saturating_add(Weight::from_ref_time(703_961).saturating_mul(r.into()))
			// Standard Error: 895
			.saturating_add(Weight::from_ref_time(16_961).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_child_role(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894`
		//  Estimated: `17954`
		// Minimum execution time: 46_187 nanoseconds.
		Weight::from_parts(44_120_614, 17954)
			// Standard Error: 4_842
			.saturating_add(Weight::from_ref_time(458_087).saturating_mul(r.into()))
			// Standard Error: 198
			.saturating_add(Weight::from_ref_time(14_333).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_unfiltered_role(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 38_783 nanoseconds.
		Weight::from_parts(37_510_902, 14399)
			// Standard Error: 15_786
			.saturating_add(Weight::from_ref_time(471_360).saturating_mul(r.into()))
			// Standard Error: 647
			.saturating_add(Weight::from_ref_time(10_314).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn join_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `628`
		//  Estimated: `13040`
		// Minimum execution time: 34_034 nanoseconds.
		Weight::from_parts(35_146_000, 13040)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:0)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3933`
		//  Estimated: `51732`
		// Minimum execution time: 67_908 nanoseconds.
		Weight::from_parts(68_870_000, 51732)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3654`
		//  Estimated: `40617`
		// Minimum execution time: 53_481 nanoseconds.
		Weight::from_parts(54_583_000, 40617)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_role_with_allowlist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3692`
		//  Estimated: `40921`
		// Minimum execution time: 60_093 nanoseconds.
		Weight::from_parts(62_618_000, 40921)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `13205`
		// Minimum execution time: 34_424 nanoseconds.
		Weight::from_parts(35_567_000, 13205)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn request_access_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3741`
		//  Estimated: `41313`
		// Minimum execution time: 55_535 nanoseconds.
		Weight::from_parts(56_577_000, 41313)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

/// Weight functions for `pallet_guild`.
impl WeightInfo for () {
	/// Storage: Guild GuildIdMap (r:1 w:1)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Guilds (r:0 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 256]`.
	fn create_guild(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `6404`
		// Minimum execution time: 25_919 nanoseconds.
		Weight::from_parts(26_956_537, 6404)
			// Standard Error: 191
			.saturating_add(Weight::from_ref_time(2_281).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 37_861 nanoseconds.
		Weight::from_parts(38_603_000, 14399)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[1, 128]`.
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_role_with_allowlist(n: u32, r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 53_902 nanoseconds.
		Weight::from_parts(42_366_297, 14399)
			// Standard Error: 1_800
			.saturating_add(Weight::from_ref_time(1_500_863).saturating_mul(n.into()))
			// Standard Error: 21_769
			.saturating_add(Weight::from_ref_time(703_961).saturating_mul(r.into()))
			// Standard Error: 895
			.saturating_add(Weight::from_ref_time(16_961).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_child_role(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894`
		//  Estimated: `17954`
		// Minimum execution time: 46_187 nanoseconds.
		Weight::from_parts(44_120_614, 17954)
			// Standard Error: 4_842
			.saturating_add(Weight::from_ref_time(458_087).saturating_mul(r.into()))
			// Standard Error: 198
			.saturating_add(Weight::from_ref_time(14_333).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	/// The range of component `s` is `[0, 256]`.
	fn create_unfiltered_role(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 38_783 nanoseconds.
		Weight::from_parts(37_510_902, 14399)
			// Standard Error: 15_786
			.saturating_add(Weight::from_ref_time(471_360).saturating_mul(r.into()))
			// Standard Error: 647
			.saturating_add(Weight::from_ref_time(10_314).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn join_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `628`
		//  Estimated: `13040`
		// Minimum execution time: 34_034 nanoseconds.
		Weight::from_parts(35_146_000, 13040)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:0)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3933`
		//  Estimated: `51732`
		// Minimum execution time: 67_908 nanoseconds.
		Weight::from_parts(68_870_000, 51732)
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3654`
		//  Estimated: `40617`
		// Minimum execution time: 53_481 nanoseconds.
		Weight::from_parts(54_583_000, 40617)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_role_with_allowlist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3692`
		//  Estimated: `40921`
		// Minimum execution time: 60_093 nanoseconds.
		Weight::from_parts(62_618_000, 40921)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `13205`
		// Minimum execution time: 34_424 nanoseconds.
		Weight::from_parts(35_567_000, 13205)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn request_access_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3741`
		//  Estimated: `41313`
		// Minimum execution time: 55_535 nanoseconds.
		Weight::from_parts(56_577_000, 41313)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
