
//! Autogenerated weights for `pallet_guild`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 19.0.0
//! DATE: 2023-04-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `turbineblade`, CPU: `AMD Ryzen 5 3600 6-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/gn-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_guild
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 20
// --output
// ./gn-pallets/pallet-guild/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn create_guild(n: u32, ) -> Weight;
	fn create_free_role() -> Weight;
	fn create_role_with_allowlist(n: u32, ) -> Weight;
	fn create_child_role() -> Weight;
	fn create_unfiltered_role() -> Weight;
	fn join_free_role() -> Weight;
	fn join_child_role() -> Weight;
	fn join_role_with_allowlist() -> Weight;
	fn join_unfiltered_role() -> Weight;
	fn leave() -> Weight;
	fn request_access_check() -> Weight;
	fn callback() -> Weight;
}

/// Weight functions for `pallet_guild`.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Guild GuildIdMap (r:1 w:1)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Guilds (r:0 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 256]`.
	fn create_guild(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `6404`
		// Minimum execution time: 25_067 nanoseconds.
		Weight::from_parts(26_357_416, 6404)
			// Standard Error: 209
			.saturating_add(Weight::from_ref_time(602).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 37_260 nanoseconds.
		Weight::from_parts(38_051_000, 14399)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[1, 128]`.
	fn create_role_with_allowlist(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 52_670 nanoseconds.
		Weight::from_parts(53_397_591, 14399)
			// Standard Error: 2_620
			.saturating_add(Weight::from_ref_time(1_471_481).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894`
		//  Estimated: `17954`
		// Minimum execution time: 50_104 nanoseconds.
		Weight::from_parts(51_187_000, 17954)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 43_151 nanoseconds.
		Weight::from_parts(43_713_000, 14399)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn join_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `628`
		//  Estimated: `13040`
		// Minimum execution time: 33_473 nanoseconds.
		Weight::from_parts(34_265_000, 13040)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:0)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3933`
		//  Estimated: `51732`
		// Minimum execution time: 66_656 nanoseconds.
		Weight::from_parts(67_878_000, 51732)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3654`
		//  Estimated: `40617`
		// Minimum execution time: 51_518 nanoseconds.
		Weight::from_parts(52_198_000, 40617)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_role_with_allowlist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3692`
		//  Estimated: `40921`
		// Minimum execution time: 59_201 nanoseconds.
		Weight::from_parts(60_184_000, 40921)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `13205`
		// Minimum execution time: 32_932 nanoseconds.
		Weight::from_parts(33_223_000, 13205)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn request_access_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3741`
		//  Estimated: `41313`
		// Minimum execution time: 53_901 nanoseconds.
		Weight::from_parts(54_332_000, 41313)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Oracle Requests (r:1 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn callback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `941`
		//  Estimated: `16267`
		// Minimum execution time: 50_044 nanoseconds.
		Weight::from_parts(51_026_000, 16267)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

impl WeightInfo for () {
	/// Storage: Guild GuildIdMap (r:1 w:1)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Guilds (r:0 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 256]`.
	fn create_guild(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `6404`
		// Minimum execution time: 25_067 nanoseconds.
		Weight::from_parts(26_357_416, 6404)
			// Standard Error: 209
			.saturating_add(Weight::from_ref_time(602).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 37_260 nanoseconds.
		Weight::from_parts(38_051_000, 14399)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[1, 128]`.
	fn create_role_with_allowlist(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 52_670 nanoseconds.
		Weight::from_parts(53_397_591, 14399)
			// Standard Error: 2_620
			.saturating_add(Weight::from_ref_time(1_471_481).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894`
		//  Estimated: `17954`
		// Minimum execution time: 50_104 nanoseconds.
		Weight::from_parts(51_187_000, 17954)
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:1)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Guilds (r:1 w:1)
	/// Proof Skipped: Guild Guilds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Nonce (r:1 w:1)
	/// Proof Skipped: Guild Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: MaxEncodedLen)
	/// Storage: Guild Roles (r:0 w:1)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	fn create_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `14399`
		// Minimum execution time: 43_151 nanoseconds.
		Weight::from_parts(43_713_000, 14399)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn join_free_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `628`
		//  Estimated: `13040`
		// Minimum execution time: 33_473 nanoseconds.
		Weight::from_parts(34_265_000, 13040)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:2 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:0)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_child_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3933`
		//  Estimated: `51732`
		// Minimum execution time: 66_656 nanoseconds.
		Weight::from_parts(67_878_000, 51732)
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_unfiltered_role() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3654`
		//  Estimated: `40617`
		// Minimum execution time: 51_518 nanoseconds.
		Weight::from_parts(52_198_000, 40617)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn join_role_with_allowlist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3692`
		//  Estimated: `40921`
		// Minimum execution time: 59_201 nanoseconds.
		Weight::from_parts(60_184_000, 40921)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:0 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `13205`
		// Minimum execution time: 32_932 nanoseconds.
		Weight::from_parts(33_223_000, 13205)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: GuildIdentity Addresses (r:1 w:0)
	/// Proof Skipped: GuildIdentity Addresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Roles (r:1 w:0)
	/// Proof Skipped: Guild Roles (max_values: None, max_size: None, mode: Measured)
	/// Storage: Oracle ActiveOperators (r:1 w:0)
	/// Proof Skipped: Oracle ActiveOperators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextOperator (r:1 w:1)
	/// Proof Skipped: Oracle NextOperator (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle NextRequestIdentifier (r:1 w:1)
	/// Proof Skipped: Oracle NextRequestIdentifier (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Oracle Requests (r:0 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	fn request_access_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3741`
		//  Estimated: `41313`
		// Minimum execution time: 53_901 nanoseconds.
		Weight::from_parts(54_332_000, 41313)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Oracle Requests (r:1 w:1)
	/// Proof Skipped: Oracle Requests (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Guild GuildIdMap (r:1 w:0)
	/// Proof Skipped: Guild GuildIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild RoleIdMap (r:1 w:0)
	/// Proof Skipped: Guild RoleIdMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Guild Members (r:1 w:1)
	/// Proof Skipped: Guild Members (max_values: None, max_size: None, mode: Measured)
	fn callback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `941`
		//  Estimated: `16267`
		// Minimum execution time: 50_044 nanoseconds.
		Weight::from_parts(51_026_000, 16267)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
}
